version: '3'

services:
  tts:
    image: triton-spark-tts:25.02
    build:
      context: .
      dockerfile: Dockerfile.server
    shm_size: '8gb'
    network_mode: "host"
    ports:
      - "8000:8000"
      - "8001:8001"
      - "8002:8002"
    environment:
      - PYTHONIOENCODING=utf-8
      - MODEL_ID=${MODEL_ID}
      - NVIDIA_VISIBLE_DEVICES=all
    runtime: nvidia
    volumes:
      - ./:/workspace
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['0']
              capabilities: [gpu]
    command: >
      /bin/bash -c "rm -rf Spark-TTS && git clone https://github.com/hillct/Spark-TTS.git && cd Spark-TTS/runtime/triton_trtllm && git checkout develop && bash run.sh 0 3"
